# Generated by Django 3.2.3 on 2021-05-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uberHome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicing',
            name='Owner_Name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicing',
            name='Service_Requested',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicing',
            name='Vehicle_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicing',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicing',
            name='paid',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicing',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
